/**
 * A reagent with the Light Eater component, generated by Antagonist Nightmares via an ability.
 *
 * A reagent that generates with the Light Eater element attached. It can be summoned to destroy any exposed lighting in an area.
 * The extent of what this can affect will be tested later
 *
 */

/datum/reagent/coalesced_shadow
	name = "Coalesced Shadow"
	description = "The "
	taste_description = "ink"
	taste_mult = 3
	reagent_state = GAS
	color = "#131313"

/datum/reagent/coalesced_shadow/New()
	. = ..()

	AddElement(/datum/element/light_eater)
