/**
 * A reagent with the Light Eater component, generated by Antagonist Nightmares via an ability.
 *
 * A reagent that generates with the Light Eater element attached. It can be summoned to destroy any exposed lighting in an area.
 * The extent of what this can affect will be tested later
 *
 */

/datum/reagent/coalesced_shadow
	name = "Coalesced Shadow"
	description = "Pure, condenced darkness. Will instantly absorb and put out any light it is exposed to."
	taste_description = "ink"
	taste_mult = 3
	reagent_state = GAS
	color = "#131313"

/datum/reagent/coalesced_shadow/New()
	. = ..()

	AddElement(/datum/element/light_eater)

/datum/reagent/consumable/coalesced_shadow/expose_mob(mob/living/exposed_mob, methods=TOUCH, reac_volume)
	. = ..()
	if(!ishuman(exposed_mob))
		return

	var/mob/living/carbon/victim = exposed_mob
	if(methods & (VAPOR) && prob(40))
		to_chat(victim, span_alert("The darkness sinks into your eyes!"))
		victim.adjust_temp_blindness(1 SECONDS)
	if(methods & INGEST)
		if(isethereal(victim)) //This is in addition to losing their lights
			to_chat(victim, span_warning("You accidentally ingest some of the shadows. It feels like something deep inside of you has just died."))
			victim.vomit(0, FALSE, FALSE, 2, FALSE, FALSE)
